### ISSUE TITLE
CDK v2 support

### ISSUE THREAD

**Issue by plumdog** [blimmer/cdk-datadog-integration#43]
Do you have any thoughts on how best to support CDK v2?

I'm not aware of a neat way of doing so while maintaining support for v1. I came up with a solution here https://github.com/isotoma/sops-secretsmanager-cdk, which allowed me to factor out non-CDK code, and provide support for v1 and v2 from one codebase, albeit with quite a lot of very similar, but not quite identical code around the CDK parts, and listing both v1 and be dependencies as peer dependencies.

Do you have any plans about how to achieve this for this project? Major version upgrade and just switch to CDK v2 only? New project for CDK v2? Shared codebase with lots of duplication? Those are the options I can think of.

I might be able to help, but I wanted to decide a direction first.

**Comment by blimmer** [comment]
Hey @plumdog - thanks for opening this ticket. I'm comfortable dropping support for CDK v1 since it's now officially in maintenance mode.

The simplest thing to do would be to upgrade the repo as-is. However, it might also be a nice opportunity to think about migrating to projen (see #44). Either way, I'd be happy to review and a PR if you've got the time to put one together.
